// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_end.proto

package grpc_end

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Controller           string            `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"`
	Action               string            `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Files                map[string][]byte `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Header               map[string]string `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_528ca8747948a9f4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *Request) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Request) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Request) GetFiles() map[string][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Request) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrgId                string   `protobuf:"bytes,3,opt,name=orgId,proto3" json:"orgId,omitempty"`
	UserLevel            int32    `protobuf:"varint,4,opt,name=userLevel,proto3" json:"userLevel,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_528ca8747948a9f4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Response) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *Response) GetUserLevel() int32 {
	if m != nil {
		return m.UserLevel
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc_end.Request")
	proto.RegisterMapType((map[string][]byte)(nil), "grpc_end.Request.FilesEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc_end.Request.HeaderEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc_end.Request.ParamsEntry")
	proto.RegisterType((*Response)(nil), "grpc_end.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndClient is the client API for End service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndClient interface {
	// 处理网关请求
	DoRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type endClient struct {
	cc *grpc.ClientConn
}

func NewEndClient(cc *grpc.ClientConn) EndClient {
	return &endClient{cc}
}

func (c *endClient) DoRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc_end.End/DoRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndServer is the server API for End service.
type EndServer interface {
	// 处理网关请求
	DoRequest(context.Context, *Request) (*Response, error)
}

func RegisterEndServer(s *grpc.Server, srv EndServer) {
	s.RegisterService(&_End_serviceDesc, srv)
}

func _End_DoRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndServer).DoRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_end.End/DoRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndServer).DoRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _End_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_end.End",
	HandlerType: (*EndServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRequest",
			Handler:    _End_DoRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_end.proto",
}

func init() { proto.RegisterFile("grpc_end.proto", fileDescriptor_528ca8747948a9f4) }

var fileDescriptor_528ca8747948a9f4 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xa5, 0x69, 0xfa, 0x67, 0xfa, 0x43, 0x74, 0x10, 0x59, 0x4a, 0x95, 0xd2, 0x53, 0x4f,
	0x3d, 0x54, 0x85, 0x56, 0xaf, 0x56, 0x2c, 0x78, 0x90, 0x7c, 0x01, 0x59, 0x93, 0xb1, 0x16, 0x63,
	0x36, 0xee, 0x6e, 0x0a, 0xbd, 0xfb, 0x0d, 0xfc, 0xc2, 0xb2, 0x7f, 0x62, 0x03, 0x45, 0xc4, 0xdb,
	0xbe, 0x79, 0xf3, 0xe6, 0xbd, 0xd9, 0x5d, 0x38, 0x58, 0xc9, 0x22, 0x79, 0xa4, 0x3c, 0x9d, 0x14,
	0x52, 0x68, 0x81, 0x9d, 0x0a, 0x8f, 0x3e, 0x43, 0x68, 0xc7, 0xf4, 0x5e, 0x92, 0xd2, 0x78, 0x06,
	0x90, 0x88, 0x5c, 0x4b, 0x91, 0x65, 0x24, 0x59, 0x30, 0x0c, 0xc6, 0xdd, 0xb8, 0x56, 0xc1, 0x13,
	0x68, 0xf1, 0x44, 0xaf, 0x45, 0xce, 0x1a, 0x96, 0xf3, 0x08, 0x2f, 0xa1, 0x55, 0x70, 0xc9, 0xdf,
	0x14, 0x0b, 0x87, 0xe1, 0xb8, 0x37, 0x3d, 0x9d, 0x7c, 0xdb, 0xf9, 0xd1, 0x93, 0x07, 0xcb, 0x2f,
	0x72, 0x2d, 0xb7, 0xb1, 0x6f, 0xc6, 0x29, 0x44, 0xcf, 0xeb, 0x8c, 0x14, 0x6b, 0x5a, 0xd5, 0x60,
	0x5f, 0x75, 0x6b, 0x68, 0x27, 0x72, 0xad, 0xc6, 0xea, 0x85, 0x78, 0x4a, 0x92, 0x45, 0x3f, 0x59,
	0xdd, 0x59, 0xde, 0x5b, 0xb9, 0xe6, 0xfe, 0x1c, 0x7a, 0xb5, 0x04, 0x78, 0x08, 0xe1, 0x2b, 0x6d,
	0xfd, 0x86, 0xe6, 0x88, 0xc7, 0x10, 0x6d, 0x78, 0x56, 0x92, 0xdf, 0xcc, 0x81, 0xab, 0xc6, 0x2c,
	0xe8, 0xcf, 0x00, 0x76, 0x31, 0x7e, 0x53, 0xfe, 0xaf, 0x2b, 0xe7, 0xd0, 0xab, 0x65, 0xf9, 0x8b,
	0xe9, 0xe8, 0x23, 0x80, 0x4e, 0x4c, 0xaa, 0x10, 0xb9, 0x22, 0x64, 0xd0, 0x56, 0x65, 0x92, 0x90,
	0x52, 0x56, 0xdc, 0x89, 0x2b, 0x68, 0x1e, 0xa4, 0x54, 0x24, 0x97, 0x69, 0xf5, 0x20, 0x0e, 0x99,
	0xc1, 0x42, 0xae, 0x96, 0x29, 0x0b, 0xdd, 0x60, 0x0b, 0x70, 0x00, 0x5d, 0xc3, 0xdf, 0xd3, 0x86,
	0x32, 0xd6, 0x1c, 0x06, 0xe3, 0x28, 0xde, 0x15, 0x10, 0xa1, 0x99, 0x72, 0xcd, 0x59, 0x64, 0xd7,
	0xb0, 0xe7, 0xe9, 0x35, 0x84, 0x8b, 0x3c, 0xc5, 0x0b, 0xe8, 0xde, 0x88, 0xea, 0x93, 0x1c, 0xed,
	0xdd, 0x78, 0x1f, 0xeb, 0x25, 0x17, 0x7a, 0xf4, 0xef, 0xa9, 0x65, 0xbf, 0xda, 0xf9, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0x95, 0xac, 0x33, 0x7c, 0x02, 0x00, 0x00,
}
